### ISSUE TITLE
MouseSimulator Coordinates are not the same MousePosition in multiscreen setup

### ISSUE THREAD

**Issue by mhusinsky** [bj-rn/VL.IO.MouseKeyGlobal#1] opened 2023-10-06 13:31 UTC
hi,
i just tried the experimental MouseSimulator in v 5.0.0.

on my 3 sceen setup (the middle sceen being the primary screen) the mouse position is not equal to the position that can be input to the MouseSimulator.

When the simulator gets coordinates 1280/720 the pointer should appear at the green position. However, it actually does appear on the red position (which is not intuitive)
![grafik](https://github.com/bj-rn/VL.IO.MouseKeyGlobal/assets/3253299/c28604d2-75ce-425d-9a13-e2cfc19fab0f)

otherwise: thanks for this great package :)

**Comment by bj-rn** [comment] 2023-10-06 13:48
I think this is caused by the following change in libuihook:
https://github.com/TolikPylypchuk/libuiohook/pull/1

I can only add a workaround by somehow remapping the coordinates, which implies adding some kind of screen info functionality.

**Comment by bj-rn** [comment] 2023-10-06 17:21
@mhusinsky  turns out it is a known and fixed bug. The fix hasn't been released as nuget yet though:
https://github.com/TolikPylypchuk/SharpHook/issues/66#issuecomment-1751131272

**Comment by bj-rn** [comment] 2023-10-09 10:33
Updated to Sharphook 5.1.0 which fixes the issue.

**Closed as completed by bj-rn** 2023-10-09 10:33 UTC
Labels: bug
